// Pins richardsonExtrap (least-squares quadratic extrapolation in h=1/N) and
// reflectionCoefficient (Gamma from R/X/Z0), the numeric cores behind the
// convergence sweep and the SWR/Smith-chart readouts.
import { describe, it, expect } from "vitest";
import { reflectionCoefficient, richardsonExtrap } from "../App";

describe("richardsonExtrap", () => {
  it("returns null for fewer than 3 points", () => {
    expect(richardsonExtrap([], [])).toBeNull();
    expect(richardsonExtrap([1], [1])).toBeNull();
    expect(richardsonExtrap([1, 0.5], [1, 2])).toBeNull();
  });

  it("recovers a0 exactly from data generated by a known quadratic in h=1/N", () => {
    const N = [17, 24, 34, 48, 68];
    const invN = N.map((n) => 1 / n);
    const a0 = 50;
    const a1 = 12;
    const a2 = -3;
    const vals = invN.map((h) => a0 + a1 * h + a2 * h * h);
    const got = richardsonExtrap(invN, vals);
    expect(got).not.toBeNull();
    expect(Math.abs((got as number) - a0)).toBeLessThan(1e-9);
  });

  it("with more points than nLast, uses only the last nLast (ignores earlier garbage)", () => {
    const N = [8, 12, 17, 24, 34, 48, 68];
    const invN = N.map((n) => 1 / n);
    const a0 = 50;
    const a1 = 12;
    const a2 = -3;
    const vals = invN.map((h) => a0 + a1 * h + a2 * h * h);
    // Corrupt the first two points (outside the default nLast=5 window)
    // with values from an unrelated function.
    vals[0] = 500;
    vals[1] = -200;
    const got = richardsonExtrap(invN, vals);
    expect(got).not.toBeNull();
    expect(Math.abs((got as number) - a0)).toBeLessThan(1e-9);
  });

  it("respects an explicit nLast smaller than the data length", () => {
    const N = [17, 24, 34, 48, 68];
    const invN = N.map((n) => 1 / n);
    const a0 = 50;
    const a1 = 12;
    const a2 = -3;
    const vals = invN.map((h) => a0 + a1 * h + a2 * h * h);
    // Corrupt everything except the last 3 points; ask for nLast=3.
    vals[0] = 999;
    vals[1] = -999;
    const got = richardsonExtrap(invN, vals, 3);
    expect(got).not.toBeNull();
    expect(Math.abs((got as number) - a0)).toBeLessThan(1e-9);
  });
});

describe("reflectionCoefficient", () => {
  it("is zero at a matched load (Z == Z0)", () => {
    const { gRe, gIm, gMag } = reflectionCoefficient(50, 0, 50);
    expect(gRe).toBeCloseTo(0, 12);
    expect(gIm).toBeCloseTo(0, 12);
    expect(gMag).toBeCloseTo(0, 12);
  });

  it("is a pure real -1 at a dead short (Z == 0)", () => {
    const { gRe, gIm, gMag } = reflectionCoefficient(0, 0, 50);
    expect(gRe).toBeCloseTo(-1, 12);
    expect(gIm).toBeCloseTo(0, 12);
    expect(gMag).toBeCloseTo(1, 12);
  });

  it("pins a reactive-load value (R == X == Z0)", () => {
    const { gRe, gIm, gMag } = reflectionCoefficient(50, 50, 50);
    expect(gRe).toBeCloseTo(0.2, 12);
    expect(gIm).toBeCloseTo(0.4, 12);
    expect(gMag).toBeCloseTo(0.447213595499958, 12);
  });
});
