// Pins richardsonExtrap (least-squares quadratic extrapolation in h=1/N) and
// reflectionCoefficient (Gamma from R/X/Z0), the numeric cores behind the
// convergence sweep and the SWR/Smith-chart readouts.
import { describe, it, expect } from "vitest";
import { reflectionCoefficient } from "../lib/format";
import { feedwiseRichardson, richardsonExtrap } from "../lib/math";

describe("richardsonExtrap", () => {
  it("returns null for fewer than 3 points", () => {
    expect(richardsonExtrap([], [])).toBeNull();
    expect(richardsonExtrap([1], [1])).toBeNull();
    expect(richardsonExtrap([1, 0.5], [1, 2])).toBeNull();
  });

  it("recovers a0 exactly from data generated by a known quadratic in h=1/N", () => {
    const N = [17, 24, 34, 48, 68];
    const invN = N.map((n) => 1 / n);
    const a0 = 50;
    const a1 = 12;
    const a2 = -3;
    const vals = invN.map((h) => a0 + a1 * h + a2 * h * h);
    const got = richardsonExtrap(invN, vals);
    expect(got).not.toBeNull();
    expect(Math.abs((got as number) - a0)).toBeLessThan(1e-9);
  });

  it("with more points than nLast, uses only the last nLast (ignores earlier garbage)", () => {
    const N = [8, 12, 17, 24, 34, 48, 68];
    const invN = N.map((n) => 1 / n);
    const a0 = 50;
    const a1 = 12;
    const a2 = -3;
    const vals = invN.map((h) => a0 + a1 * h + a2 * h * h);
    // Corrupt the first two points (outside the default nLast=5 window)
    // with values from an unrelated function.
    vals[0] = 500;
    vals[1] = -200;
    const got = richardsonExtrap(invN, vals);
    expect(got).not.toBeNull();
    expect(Math.abs((got as number) - a0)).toBeLessThan(1e-9);
  });

  it("respects an explicit nLast smaller than the data length", () => {
    const N = [17, 24, 34, 48, 68];
    const invN = N.map((n) => 1 / n);
    const a0 = 50;
    const a1 = 12;
    const a2 = -3;
    const vals = invN.map((h) => a0 + a1 * h + a2 * h * h);
    // Corrupt everything except the last 3 points; ask for nLast=3.
    vals[0] = 999;
    vals[1] = -999;
    const got = richardsonExtrap(invN, vals, 3);
    expect(got).not.toBeNull();
    expect(Math.abs((got as number) - a0)).toBeLessThan(1e-9);
  });
});

// --- feedwiseRichardson -----------------------------------------------------
// Extracted verbatim from runConverge's per-feed extrapolation block (issue
// #642 PR 5b-1): richardsonExtrap applied per feed-index column of the
// accumulated feeds_z_re / feeds_z_im rows.

describe("feedwiseRichardson", () => {
  it("returns null per feed until >= 3 points have accumulated", () => {
    // 2 feeds, 2 rows (points) so far — richardsonExtrap needs >= 3.
    const invN = [1 / 8, 1 / 12];
    const feedsZRe = [
      [10, 20],
      [11, 21],
    ];
    const feedsZIm = [
      [1, 2],
      [1.1, 2.1],
    ];
    const { feedsRe, feedsIm } = feedwiseRichardson(invN, feedsZRe, feedsZIm);
    expect(feedsRe).toEqual([null, null]);
    expect(feedsIm).toEqual([null, null]);
  });

  it("agrees per-column with richardsonExtrap once >= 3 points are in", () => {
    const N = [8, 12, 17, 24];
    const invN = N.map((n) => 1 / n);
    // Two independent feeds, each Z = a0 + a1*h + a2*h^2 with its own coeffs.
    const feed0 = { a0: 50, a1: 12, a2: -3 };
    const feed1 = { a0: 30, a1: -8, a2: 5 };
    const zOf = (c: { a0: number; a1: number; a2: number }, h: number) =>
      c.a0 + c.a1 * h + c.a2 * h * h;
    const feedsZRe = invN.map((h) => [zOf(feed0, h), zOf(feed1, h)]);
    const feedsZIm = invN.map((h) => [zOf(feed0, h) / 2, zOf(feed1, h) / 2]);

    const { feedsRe, feedsIm } = feedwiseRichardson(invN, feedsZRe, feedsZIm);

    const col = (rows: number[][], fi: number) => rows.map((row) => row[fi]);
    expect(feedsRe[0]).toBeCloseTo(richardsonExtrap(invN, col(feedsZRe, 0))!, 9);
    expect(feedsRe[1]).toBeCloseTo(richardsonExtrap(invN, col(feedsZRe, 1))!, 9);
    expect(feedsIm[0]).toBeCloseTo(richardsonExtrap(invN, col(feedsZIm, 0))!, 9);
    expect(feedsIm[1]).toBeCloseTo(richardsonExtrap(invN, col(feedsZIm, 1))!, 9);
    // And, being generated from known quadratics, recovers a0 exactly.
    expect(feedsRe[0]).toBeCloseTo(feed0.a0, 9);
    expect(feedsRe[1]).toBeCloseTo(feed1.a0, 9);
  });
});

describe("reflectionCoefficient", () => {
  it("is zero at a matched load (Z == Z0)", () => {
    const { gRe, gIm, gMag } = reflectionCoefficient(50, 0, 50);
    expect(gRe).toBeCloseTo(0, 12);
    expect(gIm).toBeCloseTo(0, 12);
    expect(gMag).toBeCloseTo(0, 12);
  });

  it("is a pure real -1 at a dead short (Z == 0)", () => {
    const { gRe, gIm, gMag } = reflectionCoefficient(0, 0, 50);
    expect(gRe).toBeCloseTo(-1, 12);
    expect(gIm).toBeCloseTo(0, 12);
    expect(gMag).toBeCloseTo(1, 12);
  });

  it("pins a reactive-load value (R == X == Z0)", () => {
    const { gRe, gIm, gMag } = reflectionCoefficient(50, 50, 50);
    expect(gRe).toBeCloseTo(0.2, 12);
    expect(gIm).toBeCloseTo(0.4, 12);
    expect(gMag).toBeCloseTo(0.447213595499958, 12);
  });
});
