// Pins richardsonExtrap (least-squares quadratic extrapolation in h=1/N) and
// reflectionCoefficient (Gamma from R/X/Z0), the numeric cores behind the
// convergence sweep and the SWR/Smith-chart readouts.
import { describe, it, expect } from "vitest";
import { reflectionCoefficient } from "../lib/format";
import {
  feedwiseRichardson,
  gammaDbFromMag,
  gammaMagFromZ,
  richardsonExtrap,
  S11_DB_FLOOR,
  VSWR_CEILING,
  vswrFromGammaMag,
} from "../lib/math";

describe("richardsonExtrap", () => {
  it("returns null for fewer than 3 points", () => {
    expect(richardsonExtrap([], [])).toBeNull();
    expect(richardsonExtrap([1], [1])).toBeNull();
    expect(richardsonExtrap([1, 0.5], [1, 2])).toBeNull();
  });

  it("recovers a0 exactly from data generated by a known quadratic in h=1/N", () => {
    const N = [17, 24, 34, 48, 68];
    const invN = N.map((n) => 1 / n);
    const a0 = 50;
    const a1 = 12;
    const a2 = -3;
    const vals = invN.map((h) => a0 + a1 * h + a2 * h * h);
    const got = richardsonExtrap(invN, vals);
    expect(got).not.toBeNull();
    expect(Math.abs((got as number) - a0)).toBeLessThan(1e-9);
  });

  it("with more points than nLast, uses only the last nLast (ignores earlier garbage)", () => {
    const N = [8, 12, 17, 24, 34, 48, 68];
    const invN = N.map((n) => 1 / n);
    const a0 = 50;
    const a1 = 12;
    const a2 = -3;
    const vals = invN.map((h) => a0 + a1 * h + a2 * h * h);
    // Corrupt the first two points (outside the default nLast=5 window)
    // with values from an unrelated function.
    vals[0] = 500;
    vals[1] = -200;
    const got = richardsonExtrap(invN, vals);
    expect(got).not.toBeNull();
    expect(Math.abs((got as number) - a0)).toBeLessThan(1e-9);
  });

  it("respects an explicit nLast smaller than the data length", () => {
    const N = [17, 24, 34, 48, 68];
    const invN = N.map((n) => 1 / n);
    const a0 = 50;
    const a1 = 12;
    const a2 = -3;
    const vals = invN.map((h) => a0 + a1 * h + a2 * h * h);
    // Corrupt everything except the last 3 points; ask for nLast=3.
    vals[0] = 999;
    vals[1] = -999;
    const got = richardsonExtrap(invN, vals, 3);
    expect(got).not.toBeNull();
    expect(Math.abs((got as number) - a0)).toBeLessThan(1e-9);
  });
});

// --- feedwiseRichardson -----------------------------------------------------
// Extracted verbatim from runConverge's per-feed extrapolation block (issue
// #642 PR 5b-1): richardsonExtrap applied per feed-index column of the
// accumulated feeds_z_re / feeds_z_im rows.

describe("feedwiseRichardson", () => {
  it("returns null per feed until >= 3 points have accumulated", () => {
    // 2 feeds, 2 rows (points) so far — richardsonExtrap needs >= 3.
    const invN = [1 / 8, 1 / 12];
    const feedsZRe = [
      [10, 20],
      [11, 21],
    ];
    const feedsZIm = [
      [1, 2],
      [1.1, 2.1],
    ];
    const { feedsRe, feedsIm } = feedwiseRichardson(invN, feedsZRe, feedsZIm);
    expect(feedsRe).toEqual([null, null]);
    expect(feedsIm).toEqual([null, null]);
  });

  it("agrees per-column with richardsonExtrap once >= 3 points are in", () => {
    const N = [8, 12, 17, 24];
    const invN = N.map((n) => 1 / n);
    // Two independent feeds, each Z = a0 + a1*h + a2*h^2 with its own coeffs.
    const feed0 = { a0: 50, a1: 12, a2: -3 };
    const feed1 = { a0: 30, a1: -8, a2: 5 };
    const zOf = (c: { a0: number; a1: number; a2: number }, h: number) =>
      c.a0 + c.a1 * h + c.a2 * h * h;
    const feedsZRe = invN.map((h) => [zOf(feed0, h), zOf(feed1, h)]);
    const feedsZIm = invN.map((h) => [zOf(feed0, h) / 2, zOf(feed1, h) / 2]);

    const { feedsRe, feedsIm } = feedwiseRichardson(invN, feedsZRe, feedsZIm);

    const col = (rows: number[][], fi: number) => rows.map((row) => row[fi]);
    expect(feedsRe[0]).toBeCloseTo(richardsonExtrap(invN, col(feedsZRe, 0))!, 9);
    expect(feedsRe[1]).toBeCloseTo(richardsonExtrap(invN, col(feedsZRe, 1))!, 9);
    expect(feedsIm[0]).toBeCloseTo(richardsonExtrap(invN, col(feedsZIm, 0))!, 9);
    expect(feedsIm[1]).toBeCloseTo(richardsonExtrap(invN, col(feedsZIm, 1))!, 9);
    // And, being generated from known quadratics, recovers a0 exactly.
    expect(feedsRe[0]).toBeCloseTo(feed0.a0, 9);
    expect(feedsRe[1]).toBeCloseTo(feed1.a0, 9);
  });
});

describe("reflectionCoefficient", () => {
  it("is zero at a matched load (Z == Z0)", () => {
    const { gRe, gIm, gMag } = reflectionCoefficient(50, 0, 50);
    expect(gRe).toBeCloseTo(0, 12);
    expect(gIm).toBeCloseTo(0, 12);
    expect(gMag).toBeCloseTo(0, 12);
  });

  it("is a pure real -1 at a dead short (Z == 0)", () => {
    const { gRe, gIm, gMag } = reflectionCoefficient(0, 0, 50);
    expect(gRe).toBeCloseTo(-1, 12);
    expect(gIm).toBeCloseTo(0, 12);
    expect(gMag).toBeCloseTo(1, 12);
  });

  it("pins a reactive-load value (R == X == Z0)", () => {
    const { gRe, gIm, gMag } = reflectionCoefficient(50, 50, 50);
    expect(gRe).toBeCloseTo(0.2, 12);
    expect(gIm).toBeCloseTo(0.4, 12);
    expect(gMag).toBeCloseTo(0.447213595499958, 12);
  });
});

// --- gammaMagFromZ / vswrFromGammaMag ---------------------------------------
// Closed-form oracle values for the gamma/VSWR-vs-frequency sweep charts
// (issue #700 unit 5). gammaMagFromZ is a wrapper over reflectionCoefficient,
// but pinned independently here — a caller that swapped the gamma/VSWR
// conversion (e.g. plotting VSWR numbers under the gamma label) must fail
// against these, not just against reflectionCoefficient's own suite.
describe("gammaMagFromZ", () => {
  it("is zero at a matched load", () => {
    expect(gammaMagFromZ(50, 0, 50)).toBeCloseTo(0, 12);
  });

  it("is 1/3 for a 2:1 real mismatch, either direction", () => {
    expect(gammaMagFromZ(100, 0, 50)).toBeCloseTo(1 / 3, 12);
    expect(gammaMagFromZ(25, 0, 50)).toBeCloseTo(1 / 3, 12);
  });

  // R == X == Z0: a real-part-only (or naive-magnitude) shortcut would read
  // this as gRe alone (0.2) — the true value needs the reactive component
  // folded in via Math.hypot, which is what distinguishes a complex |·|
  // from real-part arithmetic.
  it("is 1/sqrt(5) for a reactive load, not the real-part-only value", () => {
    const g = gammaMagFromZ(50, 50, 50);
    expect(g).toBeCloseTo(1 / Math.sqrt(5), 12);
    expect(g).not.toBeCloseTo(0.2, 3);
  });

  it("is 1 at a dead short or dead open", () => {
    expect(gammaMagFromZ(0, 0, 50)).toBeCloseTo(1, 12);
  });
});

describe("vswrFromGammaMag", () => {
  it("is 1 (perfectly matched) at |Γ| = 0", () => {
    expect(vswrFromGammaMag(0)).toBeCloseTo(1, 12);
  });

  it("is 2 at |Γ| = 1/3 (the 2:1 real-mismatch oracle pair)", () => {
    expect(vswrFromGammaMag(1 / 3)).toBeCloseTo(2, 12);
  });

  it("agrees with the gammaMagFromZ oracle pairs end to end", () => {
    expect(vswrFromGammaMag(gammaMagFromZ(50, 0, 50))).toBeCloseTo(1, 12);
    expect(vswrFromGammaMag(gammaMagFromZ(100, 0, 50))).toBeCloseTo(2, 12);
    expect(vswrFromGammaMag(gammaMagFromZ(25, 0, 50))).toBeCloseTo(2, 12);
  });

  it("clamps to the finite ceiling at and beyond |Γ| = 1", () => {
    expect(vswrFromGammaMag(1)).toBe(VSWR_CEILING);
    expect(vswrFromGammaMag(1.5)).toBe(VSWR_CEILING);
  });

  it("stays under the ceiling and monotonic below the point it clamps", () => {
    // (1+0.98)/(1-0.98) = 99 exactly, so 0.9 stays comfortably under the
    // ceiling while still exercising the un-clamped branch of the formula.
    const v = vswrFromGammaMag(0.9);
    expect(v).toBeLessThan(VSWR_CEILING);
    expect(v).toBeGreaterThan(vswrFromGammaMag(0.5));
  });
});

// S11 log-magnitude — the negative-dB VNA convention the gamma sweep view
// plots (0 dB = total reflection, dips are good). Pinned against closed
// forms so a sign flip (positive "return loss") or a base-10/ratio-20 slip
// fails here, not just in a chart eyeball.
describe("gammaDbFromMag", () => {
  it("is 0 dB at total reflection (dead short/open)", () => {
    expect(gammaDbFromMag(1)).toBeCloseTo(0, 12);
  });

  it("is 20·log10 of the magnitude, negative for any partial reflection", () => {
    expect(gammaDbFromMag(1 / 3)).toBeCloseTo(20 * Math.log10(1 / 3), 12);
    expect(gammaDbFromMag(1 / 3)).toBeCloseTo(-9.542425094393249, 12);
    expect(gammaDbFromMag(0.1)).toBeCloseTo(-20, 12);
  });

  it("floors a perfect (or numerically zero) match instead of -Infinity", () => {
    expect(gammaDbFromMag(0)).toBe(S11_DB_FLOOR);
    expect(gammaDbFromMag(1e-9)).toBe(S11_DB_FLOOR);
    expect(Number.isFinite(gammaDbFromMag(0))).toBe(true);
  });

  it("agrees with the gammaMagFromZ oracle pairs end to end", () => {
    expect(gammaDbFromMag(gammaMagFromZ(50, 0, 50))).toBe(S11_DB_FLOOR);
    expect(gammaDbFromMag(gammaMagFromZ(100, 0, 50))).toBeCloseTo(-9.5424, 4);
    expect(gammaDbFromMag(gammaMagFromZ(25, 0, 50))).toBeCloseTo(-9.5424, 4);
  });
});
