"""momwire#935 step 1: ladder the ORACLE before using it as a reference.

NEC-5 is first order in the far mesh (momwire#845) and its answer moves with
feed grading (antennaknobs#1181). #935 uses its in-band prints at 0.5 / 1 / 3 mm
below the surface as the reference the below/below grazing band never had, and
Steve's caveat is explicit: ladder the oracle first and quote a converged value
with its own error bar. A reference that has not been laddered is the mistake
#845 already priced.

Hand-written cards, uniform mesh, every wire refined by the same factor — so
there is no grading to hold fixed and no auto_mesh in the way. The documented
ground card throughout (antennaknobs#1025).
"""

import os
import re
import subprocess
import tempfile
from pathlib import Path

EXE = os.environ["NEC5_EXE"]
HALF, GAP, RAD = 2.9557, 0.025, 5.0e-4
GN = "GN 0 0 0 0 1.300000E+01 5.000000E-03 1.000000E+00 0.000000E+00 NOFILE\n"
FR = "FR 0 1 0 0 7.100000E+00 0.000000E+00\n"


def run(deck):
    with tempfile.TemporaryDirectory(prefix="nec5_935_") as td:
        (Path(td) / "m.nec").write_text(deck)
        try:
            subprocess.run(
                [EXE],
                input="m.nec\nm.out\n\n",
                text=True,
                capture_output=True,
                cwd=td,
                timeout=2400,
            )
        except subprocess.TimeoutExpired:
            return None
        out = Path(td) / "m.out"
        if not out.is_file():
            return None
        text = out.read_text(errors="replace")
    m = re.search(
        r"- - - ANTENNA INPUT PARAMETERS - - -(.*?)(?:\n\s*\n\s*\n|$)", text, re.S
    )
    for line in m.group(1).splitlines() if m else []:
        t = line.split()
        if len(t) >= 12 and re.fullmatch(r"\d+", t[0]):
            return complex(float(t[7]), float(t[8]))
    return None


def deck(z, mult):
    n_arm, n_gap = 25 * mult, 2 * mult
    return (
        "CM 935 oracle ladder\nCE\n"
        f"GW 1 {n_arm} {-HALF:.6E} 0. {z:.6E} {-GAP:.6E} 0. {z:.6E} {RAD:.6E}\n"
        f"GW 2 {n_gap} {-GAP:.6E} 0. {z:.6E} {GAP:.6E} 0. {z:.6E} {RAD:.6E}\n"
        f"GW 3 {n_arm} {GAP:.6E} 0. {z:.6E} {HALF:.6E} 0. {z:.6E} {RAD:.6E}\n"
        "GE -1 0\n" + GN + "EX 0 2 1 2 1.000000E+00 0.000000E+00\n" + FR + "XQ 0\nEN\n"
    )


print("NEC-5 as the in-band oracle, 5.9 m dipole, documented ground card")
print("depth is BELOW the surface; momwire refuses this band (0.1 deg floor)\n")
print(f"{'depth':>8s} {'x1':>22s} {'x2':>22s} {'x4':>22s} {'x8':>22s}   Richardson")
for mm in (0.5, 1.0, 3.0):
    zs = []
    for mult in (1, 2, 4, 8):
        zs.append(run(deck(-mm / 1000.0, mult)))
    cells = " ".join(
        f"{z.real:10.3f}{z.imag:+9.3f}j" if z else f"{'--':>20s}" for z in zs
    )
    # first order in the mesh: limit ~ z_fine + (z_fine - z_coarse)
    ext = (zs[3] + (zs[3] - zs[2])) if zs[2] and zs[3] else None
    e = f"   {ext.real:9.3f}{ext.imag:+9.3f}j" if ext else ""
    print(f"{mm:6.2f}mm {cells}{e}")
    if zs[2] and zs[3]:
        print(
            f"{'':8s} last step |dZ| = {abs(zs[3] - zs[2]):.4f} ohm "
            f"({100 * abs(zs[3] - zs[2]) / abs(zs[3]):.3f} % of |Z|)"
        )

# Measured 2026-09-06, NEC-5 (LLNL-CODE-746721) on this box. These are the
# values momwire#935's shape check is built on; `momwire/tests/
# golden_grazing_shape_nec5.py` is the banked form, regenerated by
# `momwire/scripts/capture_grazing_shape_nec5.py`, which cites THIS file as
# where the ladder was first run.
#
#   depth        x1                 x2                 x4                 x8
#   0.50mm  176.210 -6.6189j   176.000 -6.5627j   175.840 -6.5648j   175.690 -6.6174j
#   1.00mm  172.020 -0.3576j   171.800 -0.3367j   171.630 -0.3703j   171.460 -0.4528j
#   3.00mm  165.040+10.3630j   164.840+10.3200j   164.690+10.2600j   164.560+10.1700j
#
#   Richardson limit (first order in the mesh, z8 + (z8 - z4)) and its bar:
#     0.5 mm  175.540 -6.670j   0.1590 ohm
#     1.0 mm  171.290 -0.535j   0.1890 ohm
#     3.0 mm  164.430+10.080j   0.1581 ohm
#
# What the ladder is FOR: NEC-5 is first order in the far mesh (momwire#845),
# so a single print is not a reference. The bar is ~0.16 ohm, about 0.1 % of
# |Z| -- a tight oracle, and tighter than momwire's own mesh convergence on
# the same geometry, which is what ends up limiting the comparison.
#
# The floor arithmetic these depths were chosen for: theta = atan(2h/L) on a
# flat wire, so at L = 5.9114 m the three depths give 0.0097 / 0.0194 /
# 0.0582 deg. Only the last is inside the 0.05 deg floor momwire#935 moved
# to, and NONE was inside the old 0.1 deg floor -- which is the point. The
# 3 mm case is the geometry #935 buys; the other two stay refused by name.
