"""Generate the Windows version-resource text for PyInstaller's
``--version-file`` (issue #1507 follow-up).

The format is not YAML or JSON: PyInstaller's own loader
(``PyInstaller.utils.win32.versioninfo.load_version_info_from_text_file``)
reads the file's bytes and ``eval()``s them as a ``VSVersionInfo(...)``
Python literal, inside a module whose globals already bind
``FixedFileInfo``/``StringFileInfo``/``StringTable``/``StringStruct``/
``VarFileInfo``/``VarStruct``. So `build_version_info` below emits exactly
that literal as text; it does not construct or import those classes, because
``PyInstaller.utils.win32.versioninfo`` itself only imports on Windows
(``PyInstaller.compat.win32api`` is Windows-only) and this module must stay
importable on Linux for its own unit test.

Kept separate from build.py so the numeric-version parsing has its own
narrow unit test.
"""

from __future__ import annotations

import re

# FixedFileInfo's filevers/prodvers are two packed 32-bit DWORDs (MS/LS),
# i.e. always exactly 4 ints — there is no way to carry a 5th field, which is
# why a dev/local suffix (".dev3", "+g1234") is dropped here and kept only in
# the string fields below (FileVersion/ProductVersion), where Explorer's
# Properties -> Details shows the full string a user actually downloaded.
_RELEASE_RE = re.compile(r"^(\d+)(?:\.(\d+))?(?:\.(\d+))?")


def numeric_release(version_str: str) -> tuple[int, int, int, int]:
    """The leading (major, minor, micro) of `version_str`, zero-padded to the
    4-int tuple FixedFileInfo requires. Anything after the numeric release
    (pre-release, dev, local segment) is ignored here on purpose — it has no
    numeric slot in a Windows DWORD pair."""
    m = _RELEASE_RE.match(version_str)
    if not m:
        return (0, 0, 0, 0)
    major, minor, micro = (int(g) if g else 0 for g in m.groups())
    return (major, minor, micro, 0)


def build_version_info(
    ak_version: str,
    *,
    name: str,
    product_name: str,
    company: str,
    copyright_str: str,
) -> str:
    """The VSVersionInfo literal text, ready for `--version-file`.

    `ak_version` is the antennaknobs release string (``importlib.metadata
    .version("antennaknobs")``) — the same source the web label and the
    console banner read, so the exe's Properties -> Details, the workbench
    page and the startup line can never disagree about which release is
    running (the report this whole feature answers: a stale exe copied over
    a new `_internal` showed no version anywhere).
    """
    filevers = numeric_release(ak_version)
    # FileVersion/ProductVersion carry the full string (dev/local suffix
    # included); filevers/prodvers carry only the numeric release. Both
    # fields point at antennaknobs's OWN version deliberately — this is the
    # exe a user drags into an old folder, not momwire.
    file_version_str = ak_version
    product_version_str = ak_version
    return f"""# UTF-8
#
# Generated by scripts/freeze_workbench/version_file.py — do not hand-edit;
# it is produced fresh from the package version on every build.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers!r},
    prodvers={filevers!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', {company!r}),
        StringStruct('FileDescription', {product_name!r}),
        StringStruct('FileVersion', {file_version_str!r}),
        StringStruct('InternalName', {name!r}),
        StringStruct('LegalCopyright', {copyright_str!r}),
        StringStruct('OriginalFilename', {(name + ".exe")!r}),
        StringStruct('ProductName', {product_name!r}),
        StringStruct('ProductVersion', {product_version_str!r})])
      ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
