// GENERATED by scripts/regenerate_solve_fixtures.py — do not hand-edit.
// Representative /solve responses (issue #737), one real solve per
// design, arrays trimmed to a couple of elements. The companion
// vitest test (SolveResponse.contract.test.ts) asserts each of these
import type { SolveResponse } from "../../lib/api";

// `satisfies SolveResponse` — a key this file has that the type
// doesn't (or a type mismatch) fails `tsc --noEmit`. Re-run the
// script and update SolveResponse together when the server's shape
// changes on purpose.
import type { Projection } from "../../lib/view";

// dipoles.invvee (tests/fixtures/solve_keys_invvee.json is the same solve's key-structure sibling).
export const invveeShape = {
  "geometry": "dipoles.invvee",
  "advisories": [],
  "wires": [
    {
      "label": "wire0",
      "knot_positions": [
        [
          0.0,
          2.184661033074241,
          5.682398955738396
        ] as [number, number, number],
        [
          0.0,
          2.0779279814205287,
          5.748279007951476
        ] as [number, number, number]
      ],
      "knot_currents_re": [
        0.0,
        -0.0016752899083794857
      ],
      "knot_currents_im": [
        0.0,
        -0.00018905979915505433
      ]
    }
  ],
  "feed_wire_index": 0,
  "feed_knot_index": 20,
  "feed_position": [
    0.0,
    1.1102230246251565e-15,
    7.0
  ] as [number, number, number],
  "feed_positions": [
    {
      "name": "feed",
      "position": [
        0.0,
        1.1102230246251565e-15,
        7.0
      ] as [number, number, number]
    }
  ],
  "z_in_re": 55.17841963036039,
  "z_in_im": -9.521690585177454,
  "design_freq_mhz": 28.47,
  "measurement_freq_mhz": 28.481,
  "lambda_design_m": 10.53011794871795,
  "solve_ms": 4.092858172953129,
  "ground": false,
  "height_m": 0.0,
  "ground_eps_r": 10000000000.0,
  "ground_sigma": 0.0,
  "ground_model_applied": "free",
  "z0_ohms": 50.0,
  "multi_feed": false,
  "default_view": "yz" as Projection,
  "radiation_efficiency": 1.0,
  "power_budget": [],
  "input_power_w": 0.008799486072185744,
  "solver": "momwire",
  "k_meas_m_inv": 0.5969176207020584,
  "ground_eps_im": -0.0,
  "directivity_norm": 606.9629722094169,
  "cache_hit": false,
  "solve_id": "c61d045c1507f2842dc2579c49ccca60",
  "cuts": {
    "az_elev_deg": 15.0,
    "elev_az_deg": 0.0,
    "n_dir": 180,
    "floor_dbi": -999.0,
    "azimuth": [
      1.907,
      1.901
    ],
    "elevation": [
      1.924,
      1.923
    ],
    "diffraction": false
  }
} satisfies SolveResponse;

// wire.doublet_ladder_tuner (tests/fixtures/solve_keys_doublet_ladder_tuner.json is the same solve's key-structure sibling).
export const doubletLadderTunerShape = {
  "geometry": "wire.doublet_ladder_tuner",
  "advisories": [],
  "wires": [
    {
      "label": "wire0",
      "knot_positions": [
        [
          0.0,
          13.400300629701409,
          10.0
        ] as [number, number, number],
        [
          0.0,
          12.90584505082358,
          10.0
        ] as [number, number, number]
      ],
      "knot_currents_re": [
        0.0,
        0.000868587560482945
      ],
      "knot_currents_im": [
        0.0,
        -0.0004960829403458946
      ]
    }
  ],
  "feed_wire_index": 0,
  "feed_knot_index": 28,
  "feed_position": [
    0.0,
    -8.881784197001252e-16,
    10.0
  ] as [number, number, number],
  "feed_positions": [
    {
      "name": "feed",
      "position": [
        0.0,
        -8.881784197001252e-16,
        10.0
      ] as [number, number, number]
    }
  ],
  "z_in_re": 51.310677621288306,
  "z_in_im": 9.663598555297884,
  "design_freq_mhz": 7.1,
  "measurement_freq_mhz": 7.15,
  "lambda_design_m": 42.22428985915493,
  "solve_ms": 7.445327006280422,
  "ground": false,
  "height_m": 0.0,
  "ground_eps_r": 10000000000.0,
  "ground_sigma": 0.0,
  "ground_model_applied": "free",
  "z0_ohms": 50.0,
  "multi_feed": false,
  "default_view": "yz" as Projection,
  "radiation_efficiency": 0.9198967189554218,
  "power_budget": [
    {
      "label": "TL li\u2192feed",
      "watts": 0.0003513368892358905,
      "path": "",
      "key": "TL li\u2192feed"
    },
    {
      "label": "TwoPort rig\u2192m",
      "watts": 0.0,
      "path": "tuner",
      "key": "tuner: TwoPort rig\u2192m"
    }
  ],
  "input_power_w": 0.009410759973649534,
  "plane": "rig",
  "planes": [
    "rig",
    "li"
  ],
  "solver": "momwire",
  "k_meas_m_inv": 0.14985291906954523,
  "ground_eps_im": -0.0,
  "directivity_norm": 35.76814564809835,
  "cache_hit": false,
  "solve_id": "6227dedce17ac72c6cd97fe045051119",
  "cuts": {
    "az_elev_deg": 15.0,
    "elev_az_deg": 0.0,
    "n_dir": 180,
    "floor_dbi": -999.0,
    "azimuth": [
      2.094,
      2.085
    ],
    "elevation": [
      2.094,
      2.094
    ],
    "diffraction": false
  }
} satisfies SolveResponse;

// dipoles.invvee_catenary (tests/fixtures/solve_keys_invvee_catenary.json is the same solve's key-structure sibling).
export const invveeCatenaryShape = {
  "geometry": "dipoles.invvee_catenary",
  "advisories": [],
  "wires": [
    {
      "label": "wire0",
      "knot_positions": [
        [
          0.0,
          2.1054264902112214,
          5.678167726572962
        ] as [number, number, number],
        [
          0.0,
          1.949552189085989,
          5.757438180511613
        ] as [number, number, number]
      ],
      "knot_currents_re": [
        0.0,
        -0.002549804637741891
      ],
      "knot_currents_im": [
        0.0,
        0.0003695242879133117
      ]
    }
  ],
  "feed_wire_index": 0,
  "feed_knot_index": 14,
  "feed_position": [
    0.0,
    2.220446049250313e-16,
    7.0
  ] as [number, number, number],
  "feed_positions": [
    {
      "name": "feed",
      "position": [
        0.0,
        2.220446049250313e-16,
        7.0
      ] as [number, number, number]
    }
  ],
  "z_in_re": 51.678889072177455,
  "z_in_im": 4.438900085880874,
  "design_freq_mhz": 28.47,
  "measurement_freq_mhz": 28.489,
  "lambda_design_m": 10.53011794871795,
  "solve_ms": 9.922375902533531,
  "ground": false,
  "height_m": 0.0,
  "ground_eps_r": 10000000000.0,
  "ground_sigma": 0.0,
  "ground_model_applied": "free",
  "z0_ohms": 50.0,
  "multi_feed": false,
  "default_view": "yz" as Projection,
  "radiation_efficiency": 0.9780749565980728,
  "power_budget": [
    {
      "label": "wire loss (I\u00b2R)",
      "watts": 0.0002105740932005508,
      "path": "",
      "key": "wire loss (I\u00b2R)"
    }
  ],
  "input_power_w": 0.009604272581829467,
  "wire_length_m": 4.996458847072652,
  "wire_weight_g": 55.310799437094246,
  "rig": {
    "rig_model": "halyard",
    "apex_tension_n": 1.1434976033587336,
    "apex_tension_lbf": 0.2570684876481289,
    "end_tension_n": 1.0000000000000036,
    "end_tension_lbf": 0.2248089430997113,
    "horizontal_tension_n": 0.895154700403982,
    "wire_sag_m": 0.06408740188881157,
    "rope_sag_m": null,
    "rope_length_m": null,
    "wire_end_height_m": 5.678167726572962
  },
  "readouts": [
    {
      "label": "rig model",
      "value": "halyard",
      "unit": null,
      "group": "rigging"
    },
    {
      "label": "apex tension",
      "value": "1.143 N (0.257 lbf)",
      "unit": null,
      "group": "rigging"
    }
  ],
  "solver": "momwire",
  "k_meas_m_inv": 0.5970852883038147,
  "ground_eps_im": -0.0,
  "directivity_norm": 556.4151820321165,
  "cache_hit": false,
  "solve_id": "a5318d631e94bb828ec14a7de8c2eebf",
  "cuts": {
    "az_elev_deg": 15.0,
    "elev_az_deg": 0.0,
    "n_dir": 180,
    "floor_dbi": -999.0,
    "azimuth": [
      1.791,
      1.785
    ],
    "elevation": [
      1.811,
      1.809
    ],
    "diffraction": false
  }
} satisfies SolveResponse;
