// GENERATED by scripts/regenerate_solve_fixtures.py — do not hand-edit.
// Representative /solve responses (issue #737), one real solve per
// design, arrays trimmed to a couple of elements. The companion
// vitest test (SolveResponse.contract.test.ts) asserts each of these
import type { SolveResponse } from "../../lib/api";

// `satisfies SolveResponse` — a key this file has that the type
// doesn't (or a type mismatch) fails `tsc --noEmit`. Re-run the
// script and update SolveResponse together when the server's shape
// changes on purpose.
import type { Projection } from "../../lib/view";

// dipoles.invvee (tests/fixtures/solve_keys_invvee.json is the same solve's key-structure sibling).
export const invveeShape = {
  "geometry": "dipoles.invvee",
  "wires": [
    {
      "label": "wire0",
      "knot_positions": [
        [
          0.0,
          2.184661033074241,
          5.682398955738396
        ] as [number, number, number],
        [
          0.0,
          2.0779279814205287,
          5.748279007951476
        ] as [number, number, number]
      ],
      "knot_currents_re": [
        0.0,
        -0.0016736713661747403
      ],
      "knot_currents_im": [
        0.0,
        -0.00019465033732947229
      ]
    }
  ],
  "feed_wire_index": 0,
  "feed_knot_index": 20,
  "feed_position": [
    0.0,
    1.1102230246251565e-15,
    7.0
  ] as [number, number, number],
  "feed_positions": [
    {
      "name": "feed",
      "position": [
        0.0,
        1.1102230246251565e-15,
        7.0
      ] as [number, number, number]
    }
  ],
  "z_in_re": 55.17561022158536,
  "z_in_im": -9.717342725986786,
  "design_freq_mhz": 28.47,
  "measurement_freq_mhz": 28.481,
  "lambda_design_m": 10.53011794871795,
  "solve_ms": 4.182408098131418,
  "ground": false,
  "height_m": 0.0,
  "ground_eps_r": 10000000000.0,
  "ground_sigma": 0.0,
  "ground_model_applied": "free",
  "z0_ohms": 50.0,
  "multi_feed": false,
  "default_view": "yz" as Projection,
  "radiation_efficiency": 1.0,
  "power_budget": [],
  "input_power_w": 0.008789354966037903,
  "solver": "momwire",
  "k_meas_m_inv": 0.5969176207020584,
  "ground_eps_im": -0.0,
  "directivity_norm": 607.6625919566022,
  "cache_hit": false,
  "solve_id": "a5c45349cd3c9bc3b0dafa621d4dbfb2",
  "cuts": {
    "az_elev_deg": 15.0,
    "elev_az_deg": 0.0,
    "n_dir": 180,
    "floor_dbi": -999.0,
    "azimuth": [
      1.907,
      1.901
    ],
    "elevation": [
      1.924,
      1.923
    ]
  }
} satisfies SolveResponse;

// wire.doublet_ladder_tuner (tests/fixtures/solve_keys_doublet_ladder_tuner.json is the same solve's key-structure sibling).
export const doubletLadderTunerShape = {
  "geometry": "wire.doublet_ladder_tuner",
  "wires": [
    {
      "label": "wire0",
      "knot_positions": [
        [
          0.0,
          13.400300629701409,
          10.0
        ] as [number, number, number],
        [
          0.0,
          12.90584505082358,
          10.0
        ] as [number, number, number]
      ],
      "knot_currents_re": [
        0.0,
        0.0008688071531197113
      ],
      "knot_currents_im": [
        0.0,
        -0.0004957283375516049
      ]
    }
  ],
  "feed_wire_index": 0,
  "feed_knot_index": 28,
  "feed_position": [
    0.0,
    -8.881784197001252e-16,
    10.0
  ] as [number, number, number],
  "feed_positions": [
    {
      "name": "feed",
      "position": [
        0.0,
        -8.881784197001252e-16,
        10.0
      ] as [number, number, number]
    }
  ],
  "z_in_re": 51.3215952742601,
  "z_in_im": 9.636820920183492,
  "design_freq_mhz": 7.1,
  "measurement_freq_mhz": 7.15,
  "lambda_design_m": 42.22428985915493,
  "solve_ms": 7.117491215467453,
  "ground": false,
  "height_m": 0.0,
  "ground_eps_r": 10000000000.0,
  "ground_sigma": 0.0,
  "ground_model_applied": "free",
  "z0_ohms": 50.0,
  "multi_feed": false,
  "default_view": "yz" as Projection,
  "radiation_efficiency": 0.9199310773186768,
  "power_budget": [
    {
      "label": "TL li\u2192feed",
      "watts": 0.0003511642426188531,
      "path": "",
      "key": "TL li\u2192feed"
    },
    {
      "label": "TwoPort rig\u2192m",
      "watts": 0.0,
      "path": "tuner",
      "key": "tuner: TwoPort rig\u2192m"
    }
  ],
  "input_power_w": 0.009410678449394198,
  "plane": "rig",
  "planes": [
    "rig",
    "li"
  ],
  "solver": "momwire",
  "k_meas_m_inv": 0.14985291906954523,
  "ground_eps_im": -0.0,
  "directivity_norm": 35.76845550582586,
  "cache_hit": false,
  "solve_id": "59dc4d0a86ae30512951ebfebeeb6efd",
  "cuts": {
    "az_elev_deg": 15.0,
    "elev_az_deg": 0.0,
    "n_dir": 180,
    "floor_dbi": -999.0,
    "azimuth": [
      2.094,
      2.085
    ],
    "elevation": [
      2.094,
      2.094
    ]
  }
} satisfies SolveResponse;

// dipoles.invvee_catenary (tests/fixtures/solve_keys_invvee_catenary.json is the same solve's key-structure sibling).
export const invveeCatenaryShape = {
  "geometry": "dipoles.invvee_catenary",
  "wires": [
    {
      "label": "wire0",
      "knot_positions": [
        [
          0.0,
          2.1054264902112214,
          5.678167726572962
        ] as [number, number, number],
        [
          0.0,
          1.949552189085989,
          5.757438180511613
        ] as [number, number, number]
      ],
      "knot_currents_re": [
        0.0,
        -0.0025474425589200257
      ],
      "knot_currents_im": [
        0.0,
        9.070528556045649e-05
      ]
    }
  ],
  "feed_wire_index": 0,
  "feed_knot_index": 14,
  "feed_position": [
    0.0,
    2.220446049250313e-16,
    7.0
  ] as [number, number, number],
  "feed_positions": [
    {
      "name": "feed",
      "position": [
        0.0,
        2.220446049250313e-16,
        7.0
      ] as [number, number, number]
    }
  ],
  "z_in_re": 51.20030756631369,
  "z_in_im": -0.9381490044027425,
  "design_freq_mhz": 28.47,
  "measurement_freq_mhz": 28.489,
  "lambda_design_m": 10.53011794871795,
  "solve_ms": 7.261528167873621,
  "ground": false,
  "height_m": 0.0,
  "ground_eps_r": 10000000000.0,
  "ground_sigma": 0.0,
  "ground_model_applied": "free",
  "z0_ohms": 50.0,
  "multi_feed": false,
  "default_view": "yz" as Projection,
  "radiation_efficiency": 0.9780272478889968,
  "power_budget": [
    {
      "label": "wire loss (I\u00b2R)",
      "watts": 0.00021450435140943586,
      "path": "",
      "key": "wire loss (I\u00b2R)"
    }
  ],
  "input_power_w": 0.009762288780476398,
  "wire_length_m": 4.996458847072652,
  "wire_weight_g": 55.310799437094246,
  "rig": {
    "rig_model": "halyard",
    "apex_tension_n": 1.1434976033587336,
    "apex_tension_lbf": 0.2570684876481289,
    "end_tension_n": 1.0000000000000036,
    "end_tension_lbf": 0.2248089430997113,
    "horizontal_tension_n": 0.895154700403982,
    "wire_sag_m": 0.06408740188881157,
    "rope_sag_m": null,
    "rope_length_m": null,
    "wire_end_height_m": 5.678167726572962
  },
  "readouts": [
    {
      "label": "rig model",
      "value": "halyard",
      "unit": null,
      "group": "rigging"
    },
    {
      "label": "apex tension",
      "value": "1.143 N (0.257 lbf)",
      "unit": null,
      "group": "rigging"
    }
  ],
  "solver": "momwire",
  "k_meas_m_inv": 0.5970852883038147,
  "ground_eps_im": -0.0,
  "directivity_norm": 547.4088297400197,
  "cache_hit": false,
  "solve_id": "0e8b43b6ee8d0f1de97de515b86230a4",
  "cuts": {
    "az_elev_deg": 15.0,
    "elev_az_deg": 0.0,
    "n_dir": 180,
    "floor_dbi": -999.0,
    "azimuth": [
      1.792,
      1.786
    ],
    "elevation": [
      1.81,
      1.809
    ]
  }
} satisfies SolveResponse;
