#!/usr/bin/env bash
# Installs a pre-push (NOT pre-commit — commits should stay cheap) git hook
# that runs the same lint gate CI runs: `ruff check . && ruff format --check
# .` (issue #738). Locally this is ~40ms; the CI round trip it replaces for a
# lint-only failure is ~2.5 min.
#
# CHECK ONLY, always. Never wire this hook to `ruff check --fix` or to
# `ruff format` (the unchecked, rewriting form): pyproject.toml's
# `unfixable = ["F401"]` is a documented anti-auto-fix stance (removing an
# "unused" import can silently drop a re-export or a side-effecting import),
# and a hook that auto-fixes on every push would fight that policy on every
# push.
#
# Idempotent: re-running only ever overwrites a hook this script generated
# itself (tagged with the marker below). A hand-written or third-party
# pre-push hook is left untouched and the script exits non-zero rather than
# clobbering it.
#
# NOT installed automatically by anything in this repo (no Makefile default
# target, no postinstall, nothing in CI) — it is opt-in per checkout:
#   bash scripts/install-hooks.sh
# or:
#   make hooks

set -euo pipefail

marker="# generated-by: antennaknobs scripts/install-hooks.sh (issue #738)"

repo_root=$(git rev-parse --show-toplevel)
# --git-common-dir (not --git-dir) so this also does the right thing from a
# linked worktree, where hooks live in the shared common dir, not the
# worktree's own .git file.
git_common_dir=$(git -C "$repo_root" rev-parse --git-common-dir)
case "$git_common_dir" in
  /*) : ;;
  *) git_common_dir="$repo_root/$git_common_dir" ;;
esac

hooks_dir="$git_common_dir/hooks"
hook_path="$hooks_dir/pre-push"

mkdir -p "$hooks_dir"

if [[ -e "$hook_path" ]] && ! grep -qF "$marker" "$hook_path"; then
  echo "error: $hook_path already exists and was not generated by this script." >&2
  echo "Not overwriting it. Remove or back it up first, then re-run this script." >&2
  exit 1
fi

cat > "$hook_path" <<EOF
#!/usr/bin/env bash
$marker
#
# Runs the lint gate CI runs before a push. CHECK ONLY: never ruff --fix or
# ruff format (unchecked) — pyproject.toml's unfixable = ["F401"] is a
# documented stance that dropping an "unused" import must be a deliberate
# human decision, not something a hook autofixes on your way out.
set -euo pipefail
ruff check . && ruff format --check .
EOF

chmod +x "$hook_path"

echo "Installed pre-push hook at $hook_path"
