"""Read `records.jsonl` and write the README for #1525. No number hand-typed.

    python scratch/1525-razor-density/report.py > README.md

Every table and every D1-D5 verdict is computed from the records, so a verdict
cannot disagree with the curve it is read off. `hypotheses.md` is included
verbatim so the README still regenerates byte-for-byte.

ERROR IS AN ALL-PORT NORM: `|Z_a - Z_b| / |Z_b|` with the port impedances taken
as VECTORS, not port 0 alone. `verticals.four_square` has four driven elements
and `arrays.bowtie16x1` sixteen; scoring only the first port would let a design
converge on paper while three of its ports were still moving.

NO RECOMMENDATION ON THE DEFAULT DENSITY is produced here, deliberately. The
cost section prices 40 against 80 and stops.
"""

from __future__ import annotations

import json
import math
import statistics
import sys
from collections import Counter
from pathlib import Path

RUNGS = (21, 40, 80, 160)
SERVED = 40
REF_RUNG = 160  # bs2 at the top rung: the best available stand-in for converged
GROUNDS = ("free", "somm")
NEC5_DESIGNS = (
    "loops.skyloop_lmatch",
    "verticals.rectangle",
    "dipoles.koch_dipole",
    "verticals.four_square",
)


def load(path):
    recs, designs = {}, []
    for line in open(path, encoding="utf-8"):
        r = json.loads(line)
        recs[(r["design"], r["ground"], r["rung"], r["engine"])] = r
        if r["design"] not in designs:
            designs.append(r["design"])
    return recs, designs


def zvec(rec):
    return [complex(*p) for p in rec["z"]]


def vnorm(v):
    return math.sqrt(sum(abs(x) ** 2 for x in v))


def verr(rec_a, rec_b):
    """All-port relative error, or None when the pair is not comparable."""
    if rec_a is None or rec_b is None:
        return None
    if rec_a["status"] != "ok" or rec_b["status"] != "ok":
        return None
    a, b = zvec(rec_a), zvec(rec_b)
    if len(a) != len(b):
        return None
    den = vnorm(b)
    if den == 0:
        return None
    return vnorm([x - y for x, y in zip(a, b, strict=True)]) / den


def fit_exponent(ns, errs):
    """Least-squares p in err ~ C * N**(-p). None with fewer than 3 usable points."""
    pts = [
        (math.log(n), math.log(e))
        for n, e in zip(ns, errs, strict=True)
        if n and e and e > 0
    ]
    if len(pts) < 3:
        return None
    mx = statistics.fmean(x for x, _ in pts)
    my = statistics.fmean(y for _, y in pts)
    sxx = sum((x - mx) ** 2 for x, _ in pts)
    if sxx == 0:
        return None
    sxy = sum((x - mx) * (y - my) for x, y in pts)
    return -(sxy / sxx)


def med(vals):
    """Median, or None on an empty population -- NEVER a crash and never a
    silently-passing zero. An empty population here means "nothing was
    measured", and the D1-D5 scoring below turns that into UNSCORED rather
    than HIT: a bar that no data was tested against has not been met."""
    return statistics.median(vals) if vals else None


def quant(vals, q):
    if not vals:
        return None
    v = sorted(vals)
    return v[min(len(v) - 1, int(q * len(v)))]


def pct(x):
    return "—" if x is None else f"{100 * x:.3g} %"


def num(x, f="{:.2f}"):
    return "—" if x is None else f.format(x)


def dist_line(label, vals, f="{:.2f}"):
    if not vals:
        return f"| {label} | 0 | — | — | — | — |"
    v = sorted(vals)
    return (
        f"| {label} | {len(v)} | {f.format(statistics.median(v))} | "
        f"{f.format(v[max(0, int(0.10 * len(v)) - 1)])} | "
        f"{f.format(v[min(len(v) - 1, int(0.90 * len(v)))])} | "
        f"{f.format(v[-1])} |"
    )


DIST_HEADER = (
    "| population | n | median | p10 | p90 | max |\n|---|---:|---:|---:|---:|---:|"
)


def main(argv=None):
    path = Path(argv[0]) if argv else Path(__file__).with_name("records.jsonl")
    recs, designs = load(path)
    out = []
    w = out.append

    w("# antennaknobs#1525 — razor-2p density ladder over the catalog\n")
    w(
        "Generated by `report.py` from `records.jsonl`; every number and verdict "
        "is computed, none transcribed. `PLAN.md` registers D1–D5 and the setup. "
        "**Measurement only — no recommendation on the default density.**\n"
    )
    w(
        f"**Scope.** {len(recs)} cells over {len(designs)} designs × "
        f"{len(GROUNDS)} grounds × {len(RUNGS)} rungs. Error is an all-port norm "
        "against **bs2 at rung 160**, with bs2 at its defaults (rung 21) reported "
        "beside it.\n"
    )

    # ---------------- coverage ----------------
    w("## 1. Coverage\n")
    w("| engine | ok | refused | error | timeout |")
    w("|---|---:|---:|---:|---:|")
    for e in ("razor", "bs2", "nec5"):
        c = Counter(r["status"] for k, r in recs.items() if k[3] == e)
        if sum(c.values()):
            w(f"| `{e}` | {c['ok']} | {c['refused']} | {c['error']} | {c['timeout']} |")
    bad = [
        (k, r)
        for k, r in recs.items()
        if r["status"] != "ok" and r.get("error_type") not in (None,)
    ]
    causes = Counter(r.get("error_type") for _k, r in bad)
    if causes:
        w("")
        w(
            "Non-ok cells by cause: "
            + ", ".join(f"`{k}` × {v}" for k, v in causes.most_common())
        )
    mem = [k for k, r in recs.items() if r.get("error_type") == "MemoryError"]
    to = [k for k, r in recs.items() if r["status"] == "timeout"]
    w("")
    w(
        f"Breached the 40 GB cap: **{len(mem)}** cell(s)"
        + (
            ": " + ", ".join(f"`{d}`/{g}/×{rr}/{e}" for d, g, rr, e in mem)
            if mem
            else ""
        )
        + f". Timed out: **{len(to)}**"
        + (": " + ", ".join(f"`{d}`/{g}/×{rr}/{e}" for d, g, rr, e in to) if to else "")
        + ". Both are records, not gaps.\n"
    )
    warm_bad = [k for k, r in recs.items() if r.get("warm_matches_cold") is False]
    w(
        f"Warm solves that returned a different answer from their cold solve: "
        f"**{len(warm_bad)}**"
        + (
            " — " + ", ".join(f"`{d}`/{g}/×{rr}/{e}" for d, g, rr, e in warm_bad[:8])
            if warm_bad
            else ""
        )
        + ".\n"
    )

    # ---------------- per-design curves ----------------
    series = {}  # (design, ground) -> dict
    for d in designs:
        for g in GROUNDS:
            ref = recs.get((d, g, REF_RUNG, "bs2"))
            dflt = recs.get((d, g, RUNGS[0], "bs2"))
            ns, er, eb = [], [], []
            for rr in RUNGS:
                rz = recs.get((d, g, rr, "razor"))
                ns.append(rz.get("total_nominal_segs") if rz else None)
                er.append(verr(rz, ref))
                eb.append(verr(recs.get((d, g, rr, "bs2")), ref))
            series[(d, g)] = {
                "n": ns,
                "razor_err": er,
                "bs2_err": eb,
                "exp": fit_exponent(ns, er),
                "yardstick": verr(dflt, ref),
                "razor_vs_default": [
                    verr(recs.get((d, g, rr, "razor")), dflt) for rr in RUNGS
                ],
            }

    w("## 2. razor-2p error against bs2@160, by rung\n")
    w(DIST_HEADER)
    for g in (*GROUNDS, "both"):
        for i, rr in enumerate(RUNGS):
            vals = [
                s["razor_err"][i]
                for (d, gg), s in series.items()
                if (g == "both" or gg == g) and s["razor_err"][i] is not None
            ]
            label = f"×{rr}" + (f" ({g})" if g != "both" else " (both grounds)")
            w(dist_line(label, [100 * v for v in vals], "{:.3g} %"))
        w("| | | | | | |")
    w("")

    # ---------------- D4 yardstick ----------------
    w("## 3. Is bs2 at its defaults a usable yardstick?\n")
    ys = [s["yardstick"] for s in series.values() if s["yardstick"] is not None]
    within = sum(1 for v in ys if v <= 0.02)
    if ys:
        w(
            f"bs2 at rung 21 against bs2 at rung 160, over {len(ys)} design×ground "
            f"rows: median **{pct(med(ys))}**, p90 **{pct(quant(ys, 0.9))}**, max "
            f"**{pct(max(ys))}**. Within 2 %: **{within} of {len(ys)}** "
            f"({100 * within / len(ys):.1f} %).\n"
        )
    else:
        w("No comparable bs2 pair in the records — the yardstick is UNMEASURED.\n")
    far = sorted(
        (
            (v, d, g)
            for (d, g), s in series.items()
            if (v := s["yardstick"]) and v > 0.02
        ),
        reverse=True,
    )
    if far:
        w("Rows where bs2@defaults is more than 2 % from bs2@160:\n")
        w("| design | ground | bs2@21 vs bs2@160 |")
        w("|---|---|---:|")
        for v, d, g in far[:20]:
            w(f"| `{d}` | {g} | {pct(v)} |")
        if len(far) > 20:
            w(f"\n…and {len(far) - 20} more.")
        w("")

    # ---------------- exponents ----------------
    w("## 4. Fitted exponent of razor's error\n")
    w(
        "Least squares on `log(error)` against `log(N_nominal)` over the four "
        "rungs. First order in the mesh gives 1.\n"
    )
    exps = [s["exp"] for s in series.values() if s["exp"] is not None]
    w(DIST_HEADER)
    w(dist_line("all fittable rows", exps))
    for g in GROUNDS:
        w(
            dist_line(
                f"ground = {g}",
                [
                    s["exp"]
                    for (d, gg), s in series.items()
                    if gg == g and s["exp"] is not None
                ],
            )
        )
    w("")
    buckets = [
        ("< 0.7", 0, 0.7),
        ("0.7–1.5", 0.7, 1.5),
        ("1.5–2.5", 1.5, 2.5),
        ("≥ 2.5", 2.5, 99),
    ]
    w("| exponent band | rows | share |")
    w("|---|---:|---:|")
    for lab, lo, hi in buckets:
        n = sum(1 for e in exps if lo <= e < hi)
        share = f"{100 * n / len(exps):.1f} %" if exps else "—"
        w(f"| {lab} | {n} | {share} |")
    w("")
    w(
        f"Not fittable (fewer than three positive error points): "
        f"**{sum(1 for s in series.values() if s['exp'] is None)}** rows.\n"
    )

    # ---------------- what 80 buys over 40 ----------------
    w("## 5. What 80 buys over 40\n")
    i40, i80 = RUNGS.index(40), RUNGS.index(80)
    acc, wall, rss = [], [], []
    for (d, g), s in series.items():
        a, b = s["razor_err"][i40], s["razor_err"][i80]
        if a and b:
            acc.append(b / a)
        r40, r80 = recs.get((d, g, 40, "razor")), recs.get((d, g, 80, "razor"))
        if r40 and r80 and r40["status"] == "ok" and r80["status"] == "ok":
            if r40.get("cold_s"):
                wall.append(r80["cold_s"] / r40["cold_s"])
            if r40.get("peak_rss_mb"):
                rss.append(r80["peak_rss_mb"] / r40["peak_rss_mb"])
    w(DIST_HEADER)
    w(dist_line("accuracy — err(80)/err(40)", acc, "{:.3f}"))
    w(dist_line("cold wall — t(80)/t(40)", wall, "{:.2f}"))
    w(dist_line("peak RSS — rss(80)/rss(40)", rss, "{:.2f}"))
    w("")
    tot = {}
    for rr in RUNGS:
        cold = [
            r["cold_s"]
            for k, r in recs.items()
            if k[2] == rr
            and k[3] == "razor"
            and r["status"] == "ok"
            and r.get("cold_s")
        ]
        warm = [
            r["warm_s"]
            for k, r in recs.items()
            if k[2] == rr
            and k[3] == "razor"
            and r["status"] == "ok"
            and r.get("warm_s")
        ]
        peak = [
            r["peak_rss_mb"]
            for k, r in recs.items()
            if k[2] == rr and k[3] == "razor" and r["status"] == "ok"
        ]
        tot[rr] = (
            sum(cold),
            statistics.median(cold) if cold else None,
            statistics.median(warm) if warm else None,
            max(peak) if peak else None,
        )
    w(
        "| rung | Σ cold wall, razor, both grounds | median cold | median warm | worst peak RSS |"
    )
    w("|---:|---:|---:|---:|---:|")
    for rr in RUNGS:
        s_, mc, mw, pk = tot[rr]
        w(
            f"| ×{rr} | {s_:.1f} s | {num(mc, '{:.3f}')} s | {num(mw, '{:.3f}')} s | {num(pk, '{:.0f}')} MB |"
        )
    w("")
    w(
        "Peak RSS is a per-process high-water mark covering BOTH solves in that "
        "worker, so it cannot be split between cold and warm.\n"
    )

    # ---------------- still far off ----------------
    w("## 6. Where rung 160 is still far off\n")
    stub = sorted(
        (
            (v, d, g, series[(d, g)]["exp"])
            for (d, g), s in series.items()
            if (v := s["razor_err"][RUNGS.index(160)]) and v > 0.02
        ),
        reverse=True,
    )
    w(f"**{len(stub)}** design×ground rows still exceed 2 % at rung 160.\n")
    if stub:
        w("| design | ground | err@×160 | err@×40 | exponent | N@×160 |")
        w("|---|---|---:|---:|---:|---:|")
        for v, d, g, e in stub:
            s = series[(d, g)]
            w(
                f"| `{d}` | {g} | {pct(v)} | {pct(s['razor_err'][i40])} | "
                f"{num(e)} | {s['n'][RUNGS.index(160)]} |"
            )
    w("")

    # ---------------- NEC-5 matched density ----------------
    w("## 7. NEC-5 at matched density, on the four #1516 designs\n")
    w(
        "| design | ground | rung | razor vs NEC-5 | NEC-5 vs bs2@160 | razor vs bs2@160 |"
    )
    w("|---|---|---:|---:|---:|---:|")
    for d in NEC5_DESIGNS:
        for g in GROUNDS:
            ref = recs.get((d, g, REF_RUNG, "bs2"))
            for rr in RUNGS:
                rz, n5 = recs.get((d, g, rr, "razor")), recs.get((d, g, rr, "nec5"))
                if n5 is None:
                    continue
                w(
                    f"| `{d}` | {g} | ×{rr} | {pct(verr(rz, n5))} | "
                    f"{pct(verr(n5, ref))} | {pct(verr(rz, ref))} |"
                )
    w("")

    # ---------------- predictions ----------------
    w("## 8. Predictions D1–D5, scored\n")
    scored = []
    med_e = med(exps)
    in_band = (sum(1 for e in exps if 0.7 <= e <= 1.5) / len(exps)) if exps else None
    scored.append(
        (
            "D1",
            "exponent median in 0.8–1.3 and ≥ 70 % of rows in 0.7–1.5",
            "no fittable rows"
            if med_e is None
            else f"median {med_e:.2f}, {100 * in_band:.1f} % in band",
            None if med_e is None else (0.8 <= med_e <= 1.3 and in_band >= 0.70),
        )
    )
    # `.get` because a partial records file (a sweep still running, or a
    # --designs subset) legitimately has no row for this design, and a KeyError
    # there would make the whole report unrunnable mid-sweep.
    sky = [(series.get(("loops.skyloop_lmatch", g)) or {}).get("exp") for g in GROUNDS]
    sky = [e for e in sky if e is not None]
    scored.append(
        (
            "D2",
            "`loops.skyloop_lmatch` exponent in 1.7–2.4",
            ", ".join(f"{g} {e:.2f}" for g, e in zip(GROUNDS, sky, strict=False))
            or "not fittable",
            None if not sky else all(1.7 <= e <= 2.4 for e in sky),
        )
    )
    ma, mw_, mr = med(acc), med(wall), med(rss)
    scored.append(
        (
            "D3",
            "err(80)/err(40) median 0.45–0.60; wall ratio 3.0–5.0; RSS ratio 1.5–4.0",
            f"err {num(ma, '{:.3f}')}, wall {num(mw_)}, RSS {num(mr)}",
            None
            if None in (ma, mw_, mr)
            else (0.45 <= ma <= 0.60 and 3.0 <= mw_ <= 5.0 and 1.5 <= mr <= 4.0),
        )
    )
    frac = (within / len(ys)) if ys else None
    scored.append(
        (
            "D4",
            "bs2@defaults within 2 % of bs2@160 on ≥ 80 % of rows",
            "no comparable rows"
            if frac is None
            else f"{100 * frac:.1f} % ({within}/{len(ys)})",
            None if frac is None else frac >= 0.80,
        )
    )
    # THE DENOMINATOR IS PART OF THE PREDICTION. "fewer than 20 rows above 2 %"
    # is satisfied by a records file containing nothing at all, which is how an
    # empty gate reports itself green. D5 is scored only against rows that
    # actually produced a rung-160 error.
    scorable_160 = [
        1 for s_ in series.values() if s_["razor_err"][RUNGS.index(160)] is not None
    ]
    scored.append(
        (
            "D5",
            "fewer than 20 design×ground rows above 2 % at rung 160",
            f"{len(stub)} of {len(scorable_160)} rows with a rung-160 error",
            None if len(scorable_160) < 20 else len(stub) < 20,
        )
    )
    w("| prediction | bar | measured | verdict |")
    w("|---|---|---|---|")
    for tag, bar, got, ok in scored:
        verdict = (
            "**UNSCORED — no data**"
            if ok is None
            else ("**HIT**" if ok else "**MISS**")
        )
        w(f"| **{tag}** | {bar} | {got} | {verdict} |")
    w("")
    unscored = sum(1 for *_x, ok in scored if ok is None)
    w(
        f"Hit {sum(1 for *_x, ok in scored if ok is True)} of {len(scored)}"
        + (f", with {unscored} UNSCORED for want of data." if unscored else ".")
        + "\n"
    )

    # ---------------- appendix ----------------
    w("## 9. Appendix — every design, every rung\n")
    w("`err` is razor-2p against bs2@160, all-port norm. `N` is the nominal count.\n")
    w(
        "| design | ground | N ×21/×40/×80/×160 | err ×21 | err ×40 | err ×80 | err ×160 | exponent |"
    )
    w("|---|---|---|---:|---:|---:|---:|---:|")
    for d in designs:
        for g in GROUNDS:
            s = series[(d, g)]
            w(
                f"| `{d}` | {g} | "
                + "/".join(str(x) if x else "—" for x in s["n"])
                + " | "
                + " | ".join(pct(v) for v in s["razor_err"])
                + f" | {num(s['exp'])} |"
            )
    w("")

    notes = Path(__file__).with_name("hypotheses.md")
    if notes.is_file():
        w(notes.read_text(encoding="utf-8").rstrip())
        w("")

    sys.stdout.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
